# Generated by Django 6.1 on 2026-08-28 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_channel', models.CharField(default=models.EmailField(max_length=254), max_length=20)),
                ('dnd', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='failed', max_length=20)),
                ('failure_code', models.CharField(blank=True, choices=[('insufficient_funds', 'Insufficient Funds'), ('expired_card', 'Expired Card'), ('bank_timeout', 'Bank Timeout'), ('do_not_honor', 'Do Not Honor')], max_length=30)),
                ('attempt_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(max_length=100)),
                ('reasoning', models.TextField(max_length=50)),
                ('outcome', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.paymentattempt')),
            ],
        ),
    ]
